# Generated by Django 3.0.8 on 2020-07-28 09:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_data',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=32, null=True), max_length=1024, size=None),
        ),
    ]
