# Generated by Django 3.0.8 on 2020-07-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableApp', '0002_auto_20200728_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='col',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='rows',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
