# Generated by Django 3.0.8 on 2020-07-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableApp', '0003_auto_20200729_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default=1, max_length=132),
            preserve_default=False,
        ),
    ]
